### ISSUE TITLE
请问都可以在什么平台上跑呢？

### ISSUE THREAD

**Issue by lapsule** [Danale/DanaAirLink#1]
没搜到有这个app啊，怎么演示呢？

**Comment by di3online** [comment]
可以在AppStore和各大Android应用市场搜索Danale
市场上的版本采用的是声控
采用DanaAirLink的APP已经在测试,因为需要适配一些WiFi芯片,正在完成驱动.
也非常欢迎对WiFi芯片驱动了解的大神联系我~~
我已经适配MT7601,RTL8188
